"""Generate 3D meshes from pre-computed segmentation masks.

This script reads masks generated by segment_frame.py and uses
SAM 3D Objects to generate 3D meshes.

Run this script with the sam3d-objects environment.

Pipeline:
    1. Read segmentation masks from objects/<object_name>/mask/
    2. Use SAM 3D Objects to generate 3D mesh from each mask
    3. Save output to objects/<object_name>/mesh.glb

Usage:
    conda activate sam3d-objects
    python generate_object_meshes.py
    python generate_object_meshes.py --frame frame_00 --objects_dir objects
"""

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np
import trimesh

# Configuration
SAM3D_PATH = "/my_workspace/4DHHOI/sam-3d-objects"


def load_sam3d():
    """Load SAM 3D Objects inference pipeline."""
    notebook_path = Path(SAM3D_PATH) / "notebook"
    if str(notebook_path) not in sys.path:
        sys.path.insert(0, str(notebook_path))

    from inference import Inference

    possible_paths = [
        Path(SAM3D_PATH) / "checkpoints" / "hf" / "pipeline.yaml",
        Path(SAM3D_PATH) / "checkpoints" / "hf-download" / "checkpoints" / "pipeline.yaml",
    ]

    config_path = None
    for p in possible_paths:
        if p.exists():
            config_path = p
            break

    if config_path is None:
        tried = [str(p) for p in possible_paths]
        raise FileNotFoundError(f"SAM3D config not found. Tried: {tried}")

    print(f"Loading SAM 3D Objects from: {config_path}")
    return Inference(str(config_path), compile=False)


def apply_scale_transform(glb_obj, scale_val: float):
    """Apply uniform scale to mesh.

    Args:
        glb_obj: trimesh.Trimesh or trimesh.Scene object
        scale_val: Uniform scale value

    Returns:
        Transformed mesh object
    """
    scale_matrix = np.eye(4)
    scale_matrix[:3, :3] *= scale_val

    if isinstance(glb_obj, trimesh.Scene):
        for geom in glb_obj.geometry.values():
            geom.apply_transform(scale_matrix)
    elif isinstance(glb_obj, trimesh.Trimesh):
        glb_obj.apply_transform(scale_matrix)
    else:
        raise TypeError(f"Unexpected glb type: {type(glb_obj)}")

    return glb_obj


def generate_mesh(inference, image: np.ndarray, mask: np.ndarray) -> dict:
    """Generate 3D mesh using SAM 3D Objects.

    Args:
        inference: SAM3D Inference instance
        image: RGB image as numpy array
        mask: Binary mask as numpy array

    Returns:
        Output dictionary with glb, scale, rotation, translation
    """
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)
    if mask.dtype != bool:
        mask = mask > 0

    return inference(image, mask, seed=42)


def save_outputs(output: dict, output_dir: Path) -> None:
    """Save mesh and pose data.

    Saves:
        - output_dir/mesh.glb (scaled mesh)
        - output_dir/pose.json (scale/rotation/translation)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if "glb" not in output or output["glb"] is None:
        raise ValueError("Output does not contain a mesh ('glb').")

    glb_path = output_dir / "mesh.glb"
    output["glb"].export(str(glb_path))
    print("    Saved: mesh.glb")

    pose_data = {
        "scale": float(output["scale"][0, 0].cpu().item()),
        "rotation": output["rotation"][0].cpu().tolist(),
        "translation": output["translation"][0].cpu().tolist(),
    }
    pose_path = output_dir / "pose.json"
    with open(pose_path, "w") as f:
        json.dump(pose_data, f, indent=2)
    print("    Saved: pose.json")


def process_from_summary(summary_path: Path, sam3d) -> None:
    """Process all objects from a segmentation summary file."""
    with open(summary_path) as f:
        summary = json.load(f)

    source_image_path = summary["source_image"]
    frame_name = summary["source_frame"]

    print(f"Processing frame: {frame_name}")
    print(f"Source image: {source_image_path}")

    image_bgr = cv2.imread(source_image_path)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image_path}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    for obj_info in summary["objects"]:
        if not obj_info.get("success", False):
            print(f"\nSkipping {obj_info['object']} (segmentation failed)")
            continue

        obj_name = obj_info["object"]
        output_dir = Path(obj_info["output_dir"])
        mask_file = obj_info["mask_file"]

        print(f"\n{'=' * 50}")
        print(f"Processing: {obj_name}")

        mask_path = output_dir / mask_file
        if not mask_path.exists():
            print(f"  Error: Mask not found: {mask_path}")
            continue

        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            print(f"  Error: Could not read mask: {mask_path}")
            continue

        mask = (mask > 127).astype(np.uint8)
        print(f"  Loaded mask: {mask_file}")

        print("  Generating mesh...")
        try:
            output = generate_mesh(sam3d, image_rgb, mask)

            scale_val = output["scale"][0, 0].item()
            trans_val = output["translation"][0].cpu().numpy()
            print(f"    Scale: {scale_val:.4f}")
            print(f"    Translation: [{trans_val[0]:.4f}, {trans_val[1]:.4f}, {trans_val[2]:.4f}]")

            output["glb"] = apply_scale_transform(output["glb"], scale_val)
            print("    Applied scale transform")

            save_outputs(output, output_dir)
        except Exception as e:
            print(f"  Mesh generation failed: {e}")


def process_single_object(object_dir: Path, frame_name: str, sam3d) -> None:
    """Process a single object directory."""
    bbox_metadata_path = object_dir / "bbox" / f"{frame_name}.json"
    if not bbox_metadata_path.exists():
        print(f"Error: Bbox metadata not found: {bbox_metadata_path}")
        return

    with open(bbox_metadata_path) as f:
        metadata = json.load(f)

    obj_name = metadata["object"]
    source_image = metadata["source_image"]

    print(f"Processing: {obj_name}")
    print(f"Source image: {source_image}")

    image_bgr = cv2.imread(source_image)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    mask_path = object_dir / "mask" / f"{frame_name}.png"
    if not mask_path.exists():
        print(f"Error: Mask not found: {mask_path}")
        return

    mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
    if mask is None:
        print(f"Error: Could not read mask: {mask_path}")
        return

    mask = (mask > 127).astype(np.uint8)
    print(f"  Loaded mask: mask/{frame_name}.png")

    print("  Generating mesh...")
    try:
        output = generate_mesh(sam3d, image_rgb, mask)

        scale_val = output["scale"][0, 0].item()
        output["glb"] = apply_scale_transform(output["glb"], scale_val)
        print("    Applied scale transform")

        save_outputs(output, object_dir)
    except Exception as e:
        print(f"  Mesh generation failed: {e}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate 3D meshes from masks (run with sam3d-objects env)."
    )
    parser.add_argument(
        "--frame",
        type=str,
        default="frame_00",
        help="Frame name to process (e.g., frame_00).",
    )
    parser.add_argument(
        "--objects_dir",
        type=str,
        default="objects",
        help="Directory containing object folders with masks.",
    )
    parser.add_argument(
        "--object",
        type=str,
        default=None,
        help="Process single object (e.g., 'iron' or 'ironing_board').",
    )
    parser.add_argument(
        "--summary",
        type=str,
        default=None,
        help="Path to segmentation summary JSON (auto-detected if not provided).",
    )
    args = parser.parse_args()

    objects_dir = Path(args.objects_dir)
    if not objects_dir.is_absolute():
        objects_dir = Path(__file__).parent / objects_dir

    if not objects_dir.exists():
        print(f"Error: Objects directory not found: {objects_dir}")
        return

    print("Loading SAM 3D Objects...")
    sam3d = load_sam3d()
    print("SAM 3D Objects loaded successfully\n")

    if args.summary:
        summary_path = Path(args.summary)
        if not summary_path.exists():
            print(f"Error: Summary file not found: {summary_path}")
            return
        process_from_summary(summary_path, sam3d)

    elif args.object:
        object_dir = objects_dir / args.object.replace(" ", "_")
        if not object_dir.exists():
            print(f"Error: Object directory not found: {object_dir}")
            return
        process_single_object(object_dir, args.frame, sam3d)

    else:
        summary_path = objects_dir / f"{args.frame}_segmentation_summary.json"
        if summary_path.exists():
            process_from_summary(summary_path, sam3d)
        else:
            print(f"No summary file found, scanning for {args.frame} masks...")
            processed = False

            for obj_dir in sorted(objects_dir.iterdir()):
                if not obj_dir.is_dir():
                    continue

                mask_path = obj_dir / "mask" / f"{args.frame}.png"
                if mask_path.exists():
                    print(f"\n{'=' * 50}")
                    process_single_object(obj_dir, args.frame, sam3d)
                    processed = True

            if not processed:
                print(f"No segmentation data found for frame: {args.frame}")
                print("Run segment_frame.py first to generate masks.")
                return

    print(f"\n{'=' * 50}")
    print("Done!")


if __name__ == "__main__":
    main()
