"""Generate 3D meshes from pre-computed segmentation masks.

This script reads masks generated by segment_frame.py and uses
SAM 3D Objects to generate 3D meshes.

Run this script with the sam3d-objects environment.

Pipeline:
    1. Read segmentation masks from objects/<object_name>/mask/
    2. Use SAM 3D Objects to generate 3D mesh from each mask
    3. Save outputs to:
       - objects/<object_name>/mesh.glb   (3D mesh)
       - objects/<object_name>/points.ply (point cloud)

Usage:
    conda activate sam3d-objects
    python generate_object_meshes.py
    python generate_object_meshes.py --frame frame_00 --objects_dir objects
"""

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np

# Configuration
SAM3D_PATH = "/my_workspace/4DHHOI/sam-3d-objects"


def load_sam3d():
    """Load SAM 3D Objects inference pipeline."""
    notebook_path = Path(SAM3D_PATH) / "notebook"
    if str(notebook_path) not in sys.path:
        sys.path.insert(0, str(notebook_path))

    from inference import Inference  # noqa: E402

    # Try different checkpoint locations
    possible_paths = [
        Path(SAM3D_PATH) / "checkpoints" / "hf" / "pipeline.yaml",
        (Path(SAM3D_PATH) / "checkpoints" / "hf-download"
         / "checkpoints" / "pipeline.yaml"),
    ]

    config_path = None
    for p in possible_paths:
        if p.exists():
            config_path = p
            break

    if config_path is None:
        raise FileNotFoundError(
            f"SAM3D config not found. Tried: {[str(p) for p in possible_paths]}"
        )

    print(f"Loading SAM 3D Objects from: {config_path}")
    return Inference(str(config_path), compile=False)


def generate_mesh(inference, image: np.ndarray, mask: np.ndarray) -> dict:
    """Generate 3D mesh using SAM 3D Objects."""
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)
    if mask.dtype != bool:
        mask = mask > 0

    return inference(image, mask, seed=42)


def save_outputs(output: dict, output_dir: Path) -> None:
    """Save mesh outputs with standardized names.

    Saves:
        - output_dir/points.ply (point cloud from gaussian splatting)
        - output_dir/mesh.glb (3D mesh)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if "gs" in output:
        ply_path = output_dir / "points.ply"
        output["gs"].save_ply(str(ply_path))
        print("    Saved: points.ply")

    if "glb" in output and output["glb"] is not None:
        glb_path = output_dir / "mesh.glb"
        output["glb"].export(str(glb_path))
        print("    Saved: mesh.glb")


def process_from_summary(summary_path: Path, sam3d) -> None:
    """Process all objects from a segmentation summary file."""
    with open(summary_path) as f:
        summary = json.load(f)

    source_image_path = summary["source_image"]
    frame_name = summary["source_frame"]

    print(f"Processing frame: {frame_name}")
    print(f"Source image: {source_image_path}")

    # Load source image
    image_bgr = cv2.imread(source_image_path)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image_path}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    for obj_info in summary["objects"]:
        if not obj_info.get("success", False):
            print(f"\nSkipping {obj_info['object']} (segmentation failed)")
            continue

        obj_name = obj_info["object"]
        output_dir = Path(obj_info["output_dir"])
        mask_file = obj_info["mask_file"]  # Now "mask/frame_xx.png"

        print(f"\n{'='*50}")
        print(f"Processing: {obj_name}")

        # Load mask from mask/ subdirectory
        mask_path = output_dir / mask_file
        if not mask_path.exists():
            print(f"  Error: Mask not found: {mask_path}")
            continue

        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        mask = (mask > 127).astype(np.uint8)
        print(f"  Loaded mask: {mask_file}")

        # Generate mesh
        print("  Generating mesh...")
        try:
            output = generate_mesh(sam3d, image_rgb, mask)
            save_outputs(output, output_dir)
        except Exception as e:
            print(f"  Mesh generation failed: {e}")


def process_single_object(
    object_dir: Path,
    frame_name: str,
    sam3d,
) -> None:
    """Process a single object directory."""
    # Find bbox metadata file (contains source_image info)
    bbox_metadata_path = object_dir / "bbox" / f"{frame_name}.json"
    if not bbox_metadata_path.exists():
        print(f"Error: Bbox metadata not found: {bbox_metadata_path}")
        return

    with open(bbox_metadata_path) as f:
        metadata = json.load(f)

    obj_name = metadata["object"]
    source_image = metadata["source_image"]

    print(f"Processing: {obj_name}")
    print(f"Source image: {source_image}")

    # Load source image
    image_bgr = cv2.imread(source_image)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    # Load mask from mask/ subdirectory
    mask_path = object_dir / "mask" / f"{frame_name}.png"
    if not mask_path.exists():
        print(f"Error: Mask not found: {mask_path}")
        return

    mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
    mask = (mask > 127).astype(np.uint8)
    print(f"  Loaded mask: mask/{frame_name}.png")

    # Generate mesh
    print("  Generating mesh...")
    try:
        output = generate_mesh(sam3d, image_rgb, mask)
        save_outputs(output, object_dir)
    except Exception as e:
        print(f"  Mesh generation failed: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate 3D meshes from masks (run with sam3d-objects env)."
    )
    parser.add_argument(
        "--frame",
        type=str,
        default="frame_00",
        help="Frame name to process (e.g., frame_00).",
    )
    parser.add_argument(
        "--objects_dir",
        type=str,
        default="objects",
        help="Directory containing object folders with masks.",
    )
    parser.add_argument(
        "--object",
        type=str,
        default=None,
        help="Process single object (e.g., 'iron' or 'ironing_board').",
    )
    parser.add_argument(
        "--summary",
        type=str,
        default=None,
        help="Path to segmentation summary JSON (auto-detected if not provided).",
    )
    args = parser.parse_args()

    objects_dir = Path(args.objects_dir)
    if not objects_dir.is_absolute():
        objects_dir = Path(__file__).parent / objects_dir

    if not objects_dir.exists():
        print(f"Error: Objects directory not found: {objects_dir}")
        return

    # Load SAM 3D Objects
    print("Loading SAM 3D Objects...")
    sam3d = load_sam3d()
    print("SAM 3D Objects loaded successfully\n")

    if args.summary:
        # Process from explicit summary file
        summary_path = Path(args.summary)
        if not summary_path.exists():
            print(f"Error: Summary file not found: {summary_path}")
            return
        process_from_summary(summary_path, sam3d)

    elif args.object:
        # Process single object
        object_dir = objects_dir / args.object.replace(" ", "_")
        if not object_dir.exists():
            print(f"Error: Object directory not found: {object_dir}")
            return
        process_single_object(object_dir, args.frame, sam3d)

    else:
        # Try to find summary file
        summary_path = objects_dir / f"{args.frame}_segmentation_summary.json"
        if summary_path.exists():
            process_from_summary(summary_path, sam3d)
        else:
            # Process all object directories that have the frame's mask
            print(f"No summary file found, scanning for {args.frame} masks...")
            processed = False
            for obj_dir in sorted(objects_dir.iterdir()):
                if not obj_dir.is_dir():
                    continue
                # Check for mask in new structure: mask/frame_xx.png
                mask_path = obj_dir / "mask" / f"{args.frame}.png"
                if mask_path.exists():
                    print(f"\n{'='*50}")
                    process_single_object(obj_dir, args.frame, sam3d)
                    processed = True

            if not processed:
                print(f"No segmentation data found for frame: {args.frame}")
                print("Run segment_frame.py first to generate masks.")
                return

    print(f"\n{'='*50}")
    print("Done!")


if __name__ == "__main__":
    main()
