"""
Generate 3D meshes from pre-computed first-frame segmentation masks.

This script reads a segmentation summary JSON generated by
Segment_First_Frame/segment_first_frame.py and uses SAM 3D Objects to generate
canonical 3D meshes.

Run this script with the sam3d-objects environment.

Pipeline:
    1. Read segmentation summary JSON from Segment_First_Frame/output/<video_xx>
    2. Use SAM 3D Objects to generate 3D mesh from each object mask
    3. Save output to Generate_Object_Mesh/output/<video_xx>/<object_slug>:
        - mesh.<format> (canonical mesh)
        - pose.json (transform keys: rotation, translation, scale)
        - mesh_posed.<format> (mesh transformed to camera frame)
        - mesh_posed_overlay.png (posed mesh overlaid on source image)
    4. Save combined overlay:
        - Generate_Object_Mesh/output/<video_xx>/<frame_name>_all_objects_overlay.png

Coordinate System Notes:
    - SAM 3D Objects transforms are in Z-up coordinate system.
    - SAM 3D Objects ouput PLY are in PyTorch3D format (Z-up).
    - SAM 3D Objects output GLB are converted into PyTorch3D format (Z-up) after Y2Z rotation.
    - GLB workflow:
        1. Convert mesh from Y-up to Z-up
        2. Apply transforms (scale -> rotate -> translate)
        3. Convert back to Y-up only for GLB export
    - PLY workflow:
        1. Use SAM3D mesh output directly (already Z-up)
        2. Apply transforms (scale -> rotate -> translate) in Z-up
        3. Keep Z-up as-is for PLY export

Rendering Notes (from render_posed_mesh.py):
    - PyTorch3D uses: +X is left, +Y is up
    - Screen space uses: +X is right, +Y is down
    - Convert coordinates with F_P3D_TO_CV before projection
    - Source: https://github.com/facebookresearch/sam-3d-objects/issues/56
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Optional

import cv2
import numpy as np
import torch
import trimesh

# Configuration
SAM3D_PATH = "/my_workspace/4DHHOI/sam-3d-objects"

KEYS_TO_SAVE = {
    "6drotation_normalized",
    "rotation",
    "translation",
    "scale",
    "translation_scale",
}


# =============================================================================
# Coordinate Transformation Utilities
# =============================================================================
# GLB files are stored in Y-up coordinate system.
# SAM 3D Objects outputs transforms in Z-up coordinate system.
# We need to convert between these two coordinate systems.

# Rotation matrix to convert Y-up to Z-up coordinates
# This rotates vertices so that Y-up becomes Z-up
R_Y_UP_TO_Z_UP = np.array([
    [1, 0, 0],
    [0, 0, -1],
    [0, 1, 0],
], dtype=np.float32)

# Rotation matrix to convert Z-up to Y-up coordinates (inverse of above)
R_Z_UP_TO_Y_UP = np.array([
    [1, 0, 0],
    [0, 0, 1],
    [0, -1, 0],
], dtype=np.float32)

# P3D camera coords (+X left, +Y up, +Z forward) to OpenCV (+X right, +Y down, +Z forward)
F_P3D_TO_CV = np.diag([-1.0, -1.0, 1.0]).astype(np.float32)

SENSOR_WIDTH_MM = 36.0  # Full-frame sensor width for focal length conversion
SENSOR_HEIGHT_MM = 24.0  # Full-frame sensor height for focal length conversion
DEFAULT_FOCAL_LENGTH_MM = 24.0


def estimate_camera_intrinsics_from_moge(
    sam3d: Any,
    image_rgb: np.ndarray,
    sensor_width_mm: float = SENSOR_WIDTH_MM,
    sensor_height_mm: float = SENSOR_HEIGHT_MM,
) -> Optional[Dict[str, Any]]:
    """Estimate camera intrinsics from MoGe and derive focal lengths in mm."""
    try:
        pipeline = getattr(sam3d, "_pipeline", None)
        if pipeline is None:
            raise AttributeError("SAM3D inference object has no '_pipeline' attribute")

        depth_model = getattr(pipeline, "depth_model", None)
        if depth_model is None:
            raise AttributeError("SAM3D pipeline has no 'depth_model' attribute")

        h, w = image_rgb.shape[:2]
        image_tensor = torch.from_numpy(image_rgb).permute(2, 0, 1).float() / 255.0

        with torch.no_grad():
            depth_output = depth_model(image_tensor)

        intrinsics = depth_output.get("intrinsics", None)
        if intrinsics is None:
            raise ValueError("MoGe output did not contain 'intrinsics'")

        if hasattr(intrinsics, "detach"):
            intrinsics = intrinsics.detach().cpu().numpy()
        else:
            intrinsics = np.asarray(intrinsics)

        if intrinsics.ndim == 3:
            intrinsics = intrinsics[0]

        # MoGe intrinsics are normalized to image size.
        fx_px = float(intrinsics[0, 0]) * w
        fy_px = float(intrinsics[1, 1]) * h
        cx_px = float(intrinsics[0, 2]) * w
        cy_px = float(intrinsics[1, 2]) * h

        focal_mm_x = fx_px * sensor_width_mm / float(w)
        # Not required in camera_intrinsics.json atm.
        # focal_mm_y = fy_px * sensor_height_mm / float(h)

        intrinsics_px = np.array(
            [
                [fx_px, 0.0, cx_px],
                [0.0, fy_px, cy_px],
                [0.0, 0.0, 1.0],
            ],
            dtype=np.float32,
        )

        # Recommended single lens value for Blender with sensor fit=HORIZONTAL.
        focal_mm_recommended = focal_mm_x

        camera_info = {
            "source": "moge_from_sam3d_depth_model",
            "intrinsics_pixels_3x3": intrinsics_px.tolist(),
            "blender_recommendation": {
                "sensor_fit": "HORIZONTAL",
                "lens_mm": float(focal_mm_recommended),
                "sensor_width_mm": float(sensor_width_mm),
                "sensor_height_mm": float(sensor_height_mm),
                "note": "Lens uses fx with full-frame horizontal fit.",
            },
        }

        print(
            "Auto-estimated intrinsics from MoGe: "
            f"fx={fx_px:.1f}px, fy={fy_px:.1f}px | "
            f"lens={focal_mm_recommended:.2f}mm (recommended)"
        )
        return camera_info

    except Exception as e:
        print(f"Warning: failed to estimate intrinsics from MoGe ({e}).")
        return None


def save_camera_intrinsics_json(camera_info: Dict[str, Any], output_path: Path) -> None:
    """Save camera intrinsics metadata to JSON."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(camera_info, f, indent=2)
    print(f"Saved: {output_path}")


def _to_numpy(value: Any) -> Any:
    """Convert torch-like values to numpy when possible."""
    if value is None:
        return None
    if hasattr(value, "detach"):
        value = value.detach()
    if hasattr(value, "cpu"):
        value = value.cpu()
    if hasattr(value, "numpy"):
        value = value.numpy()
    return value


def _as_bgr_image(image: np.ndarray) -> np.ndarray:
    """Return a BGR copy suitable for cv2 drawing."""
    if image.ndim == 3 and image.shape[2] == 3:
        return cv2.cvtColor(image.copy(), cv2.COLOR_RGB2BGR)
    return image.copy()


def _get_mesh_vertex_colors(mesh: trimesh.Trimesh) -> Optional[np.ndarray]:
    """Return per-vertex colors if available."""
    visual = getattr(mesh, "visual", None)
    colors = getattr(visual, "vertex_colors", None)
    return None if colors is None else np.asarray(colors)


def _project_mesh_vertices(
    mesh: trimesh.Trimesh,
    image_height: int,
    image_width: int,
    mesh_is_y_up: bool,
    focal_length_mm: float,
) -> Optional[tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
    """Project visible mesh vertices to pixel coordinates."""
    vertices = np.asarray(mesh.vertices, dtype=np.float32)
    if vertices.size == 0:
        return None

    vertices_z_up = vertices @ R_Y_UP_TO_Z_UP.T if mesh_is_y_up else vertices
    valid_mask = vertices_z_up[:, 2] > 0.1
    if not np.any(valid_mask):
        return None

    pts_valid_cv = vertices_z_up[valid_mask] @ F_P3D_TO_CV.T
    z_valid = pts_valid_cv[:, 2]
    focal_px = float(focal_length_mm) * image_width / SENSOR_WIDTH_MM
    cx, cy = image_width / 2.0, image_height / 2.0

    u = ((pts_valid_cv[:, 0] * focal_px) / z_valid + cx).astype(np.int32)
    v = ((pts_valid_cv[:, 1] * focal_px) / z_valid + cy).astype(np.int32)

    in_view = (u >= 0) & (u < image_width) & (v >= 0) & (v < image_height)
    if not np.any(in_view):
        return None

    return u[in_view], v[in_view], valid_mask, in_view


def _draw_projected_vertices(
    canvas_bgr: np.ndarray,
    u: np.ndarray,
    v: np.ndarray,
    point_radius: int,
    fallback_color: tuple[int, int, int],
    vertex_colors: Optional[np.ndarray] = None,
    valid_mask: Optional[np.ndarray] = None,
    in_view: Optional[np.ndarray] = None,
) -> None:
    """Draw projected points using vertex colors when available."""
    if vertex_colors is not None and valid_mask is not None and in_view is not None:
        colors = np.asarray(vertex_colors)[valid_mask][in_view]
        for x, y, c in zip(u, v, colors):
            cv2.circle(
                canvas_bgr,
                (int(x), int(y)),
                point_radius,
                (int(c[2]), int(c[1]), int(c[0])),
                -1,
            )
        return

    for x, y in zip(u, v):
        cv2.circle(canvas_bgr, (int(x), int(y)), point_radius, fallback_color, -1)


def _generate_distinct_bgr_colors(num_colors: int) -> list[tuple[int, int, int]]:
    """Generate distinct colors using HSV hue spacing."""
    if num_colors <= 0:
        return []
    colors = []
    for i in range(num_colors):
        hue = int(180 * i / num_colors)
        hsv_color = np.array([[[hue, 255, 255]]], dtype=np.uint8)
        bgr_color = cv2.cvtColor(hsv_color, cv2.COLOR_HSV2BGR)[0, 0]
        colors.append((int(bgr_color[0]), int(bgr_color[1]), int(bgr_color[2])))
    return colors


def render_posed_mesh_overlay(
    image: np.ndarray,
    posed_mesh: trimesh.Trimesh,
    mesh_is_y_up: bool = True,
    focal_length_mm: float = 50.0,
    color: tuple = (0, 255, 0),
    point_radius: int = 1,
) -> np.ndarray:
    """Render posed mesh vertices overlaid on an image.

    Perspective projection uses a coordinate conversion matrix:
        P3D (+X left, +Y up, +Z forward) to OpenCV
        (+X right, +Y down, +Z forward).

    Args:
        image: RGB image as numpy array (H, W, 3).
        posed_mesh: Mesh in either Y-up or Z-up coordinates.
        mesh_is_y_up: Whether posed_mesh vertices are Y-up.
        focal_length_mm: Focal length in millimeters (default: 50mm).
        color: BGR color tuple for rendering vertices.
        point_radius: Radius of rendered points.

    Returns:
        Image with mesh vertices overlaid (BGR format for cv2).
    """
    h, w = image.shape[:2]
    result = _as_bgr_image(image)
    projected = _project_mesh_vertices(posed_mesh, h, w, mesh_is_y_up, focal_length_mm)
    if projected is None:
        return result

    u, v, valid_mask, in_view = projected
    _draw_projected_vertices(
        result,
        u,
        v,
        point_radius=point_radius,
        fallback_color=color,
        vertex_colors=_get_mesh_vertex_colors(posed_mesh),
        valid_mask=valid_mask,
        in_view=in_view,
    )
    return result


def render_all_posed_meshes_overlay(
    image: np.ndarray,
    posed_meshes: list,
    object_names: list,
    mesh_is_y_up: bool = True,
    focal_length_mm: float = 50.0,
    point_radius: int = 1,
) -> np.ndarray:
    """Render multiple posed meshes overlaid on a single image.

    Each object gets a distinct color if vertex colors are not available.

    Args:
        image: RGB image as numpy array (H, W, 3).
        posed_meshes: List of meshes in either Y-up or Z-up coordinates.
        object_names: List of object names (for labeling).
        mesh_is_y_up: Whether meshes are in Y-up coordinates.
        focal_length_mm: Focal length in millimeters (default: 50mm).
        point_radius: Radius of rendered points.

    Returns:
        Image with all mesh vertices overlaid (BGR format).
    """
    h, w = image.shape[:2]
    result = _as_bgr_image(image)
    object_colors = _generate_distinct_bgr_colors(len(posed_meshes))

    for idx, (posed_mesh, _) in enumerate(zip(posed_meshes, object_names)):
        projected = _project_mesh_vertices(
            posed_mesh,
            h,
            w,
            mesh_is_y_up=mesh_is_y_up,
            focal_length_mm=focal_length_mm,
        )
        if projected is None:
            continue

        u, v, valid_mask, in_view = projected
        _draw_projected_vertices(
            result,
            u,
            v,
            point_radius=point_radius,
            fallback_color=object_colors[idx],
            vertex_colors=_get_mesh_vertex_colors(posed_mesh),
            valid_mask=valid_mask,
            in_view=in_view,
        )

    # Add legend with object names and fallback colors.
    y_offset = 30
    for obj_name, color in zip(object_names, object_colors):
        cv2.rectangle(result, (10, y_offset - 15), (30, y_offset), color, -1)
        cv2.putText(
            result, obj_name, (40, y_offset), cv2.FONT_HERSHEY_SIMPLEX,
            0.5, (255, 255, 255), 1, cv2.LINE_AA
        )
        y_offset += 25

    return result


def quaternion_to_rotation_matrix(quat: np.ndarray) -> np.ndarray:
    """Convert quaternion (w, x, y, z) to 3x3 rotation matrix.

    PyTorch3D uses (w, x, y, z) quaternion convention.

    Args:
        quat: Quaternion as numpy array of shape (4,) in (w, x, y, z) format.

    Returns:
        3x3 rotation matrix as numpy array.
    """
    w, x, y, z = quat

    # Normalize quaternion
    norm = np.sqrt(w*w + x*x + y*y + z*z)
    w, x, y, z = w/norm, x/norm, y/norm, z/norm

    # Build rotation matrix
    rot = np.array([
        [1 - 2*(y*y + z*z), 2*(x*y - z*w), 2*(x*z + y*w)],
        [2*(x*y + z*w), 1 - 2*(x*x + z*z), 2*(y*z - x*w)],
        [2*(x*z - y*w), 2*(y*z + x*w), 1 - 2*(x*x + y*y)],
    ], dtype=np.float32)

    return rot


def quaternion_to_euler_xyz_degrees(quat: np.ndarray) -> np.ndarray:
    """Convert quaternion (w, x, y, z) to Euler XYZ angles in degrees."""
    w, x, y, z = quat

    norm = np.sqrt(w * w + x * x + y * y + z * z)
    w, x, y, z = w / norm, x / norm, y / norm, z / norm

    # XYZ Tait-Bryan angles
    t0 = 2.0 * (w * x + y * z)
    t1 = 1.0 - 2.0 * (x * x + y * y)
    roll_x = np.arctan2(t0, t1)

    t2 = 2.0 * (w * y - z * x)
    t2 = np.clip(t2, -1.0, 1.0)
    pitch_y = np.arcsin(t2)

    t3 = 2.0 * (w * z + x * y)
    t4 = 1.0 - 2.0 * (y * y + z * z)
    yaw_z = np.arctan2(t3, t4)

    return np.degrees(np.array([roll_x, pitch_y, yaw_z], dtype=np.float32))


def apply_transform_to_vertices(
    vertices: np.ndarray,
    scale: np.ndarray,
    rotation: np.ndarray,
    translation: np.ndarray,
) -> np.ndarray:
    """Apply scale, rotation, and translation to vertices.

    Transform order (same as PyTorch3D Transform3d composition):
        1. Scale
        2. Rotate
        3. Translate

    Args:
        vertices: (N, 3) array of vertex positions.
        scale: (3,) array of scale factors.
        rotation: (3, 3) rotation matrix.
        translation: (3,) translation vector.

    Returns:
        (N, 3) array of transformed vertices.
    """
    # 1. Apply scale
    scaled = vertices * scale

    # 2. Apply rotation
    # PyTorch3D Transform3d.rotate(R) uses v @ R convention
    # Our quaternion_to_rotation_matrix produces the same matrix as PyTorch3D
    rotated = scaled @ rotation

    # 3. Apply translation
    translated = rotated + translation

    return translated


def create_posed_mesh(
    canonical_mesh: trimesh.Trimesh,
    rotation_quat: np.ndarray,
    translation: np.ndarray,
    scale: np.ndarray,
    canonical_is_y_up: bool = True,
) -> trimesh.Trimesh:
    """Create a posed mesh from canonical mesh and transforms.

    Coordinate System Handling:
        - Input canonical mesh can be Y-up or Z-up.
        - SAM 3D Objects transforms are in Z-up.
        - If canonical mesh is Y-up (GLB path):
            1. Convert vertices from Y-up to Z-up.
            2. Apply transforms in Z-up space.
            3. Convert back to Y-up for export.
        - If canonical mesh is Z-up (PLY path):
            1. Apply transforms in Z-up space directly.
            2. Keep Z-up for export.

    Args:
        canonical_mesh: The canonical mesh.
        rotation_quat: Quaternion (w, x, y, z) from SAM 3D Objects.
        translation: Translation vector (3,) from SAM 3D Objects.
        scale: Scale factors (3,) from SAM 3D Objects.
        canonical_is_y_up: Whether canonical_mesh is in Y-up coordinates.

    Returns:
        Posed mesh in Y-up (GLB) or Z-up (PLY) coordinates.
    """
    # Get vertices from canonical mesh
    vertices = np.array(canonical_mesh.vertices, dtype=np.float32)

    if canonical_is_y_up:
        vertices = vertices @ R_Y_UP_TO_Z_UP.T

    # Convert quaternion to rotation matrix
    rotation_matrix = quaternion_to_rotation_matrix(rotation_quat)

    # Apply transforms in Z-up space
    vertices_posed = apply_transform_to_vertices(
        vertices,
        scale,
        rotation_matrix,
        translation,
    )

    if canonical_is_y_up:
        vertices_out = vertices_posed @ R_Z_UP_TO_Y_UP.T
    else:
        vertices_out = vertices_posed

    # Create new mesh with transformed vertices
    posed_mesh = canonical_mesh.copy()
    posed_mesh.vertices = vertices_out

    return posed_mesh


def load_sam3d():
    """Load SAM 3D Objects inference pipeline."""
    notebook_path = Path(SAM3D_PATH) / "notebook"
    if str(notebook_path) not in sys.path:
        sys.path.insert(0, str(notebook_path))

    from inference import Inference

    possible_paths = [
        Path(SAM3D_PATH) / "checkpoints" / "hf" / "pipeline.yaml",
        Path(SAM3D_PATH)
        / "checkpoints"
        / "hf-download"
        / "checkpoints"
        / "pipeline.yaml",
    ]

    config_path = None
    for p in possible_paths:
        if p.exists():
            config_path = p
            break

    if config_path is None:
        tried = [str(p) for p in possible_paths]
        raise FileNotFoundError(f"SAM3D config not found. Tried: {tried}")

    print(f"Loading SAM 3D Objects from: {config_path}")
    return Inference(str(config_path), compile=False)


def generate_mesh(inference, image: np.ndarray, mask: np.ndarray) -> dict:
    """Generate 3D mesh using SAM 3D Objects.

    Args:
        inference: SAM3D Inference instance
        image: RGB image as numpy array
        mask: Binary mask as numpy array

    Returns:
        Output dictionary with mesh/glb and transform fields.
    """
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)
    if mask.dtype != bool:
        mask = mask > 0

    return inference(image, mask, seed=42)


def _to_jsonable(value: Any) -> Any:
    """Convert common tensor/numpy types to JSON-serializable Python types."""
    if value is None:
        return None

    value = _to_numpy(value)

    if isinstance(value, np.ndarray):
        if value.size == 1:
            return float(value.reshape(-1)[0])
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


def sam3d_mesh_to_trimesh(sam3d_mesh: Any) -> trimesh.Trimesh:
    """Convert SAM3D mesh output to trimesh."""
    vertices = _to_numpy(sam3d_mesh.vertices)
    faces = _to_numpy(sam3d_mesh.faces)

    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)

    vertex_attrs = _to_numpy(getattr(sam3d_mesh, "vertex_attrs", None))
    if vertex_attrs is not None:
        if getattr(vertex_attrs, "ndim", 0) == 2 and vertex_attrs.shape[1] >= 3:
            vertex_colors = np.clip(vertex_attrs[:, :3] * 255.0, 0, 255).astype(np.uint8)
            mesh.visual.vertex_colors = vertex_colors

    return mesh


def _resolve_canonical_mesh(
    output: Dict[str, Any],
    mesh_format: str,
) -> tuple[trimesh.Trimesh, str, bool]:
    """Select canonical mesh from SAM3D output."""
    if mesh_format == "glb":
        canonical_mesh = output.get("glb")
        if canonical_mesh is None:
            raise ValueError("Output does not contain a mesh ('glb').")
        return canonical_mesh, "glb", True

    mesh_data = output.get("mesh")
    if mesh_data is None:
        raise ValueError("Output does not contain a mesh ('mesh').")
    return sam3d_mesh_to_trimesh(mesh_data[0]), "ply", False


def _extract_pose_components(output: Dict[str, Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Extract rotation/translation/scale arrays from SAM3D output."""
    required_keys = {"rotation", "translation", "scale"}
    missing_keys = sorted(required_keys.difference(output))
    if missing_keys:
        raise ValueError(f"Missing transform keys for posed mesh: {missing_keys}")

    rotation_quat = np.asarray(_to_jsonable(output["rotation"]), dtype=np.float32).flatten()
    translation = np.asarray(_to_jsonable(output["translation"]), dtype=np.float32).flatten()
    scale = np.asarray(_to_jsonable(output["scale"]), dtype=np.float32).flatten()
    return rotation_quat, translation, scale


def _build_transform_data(
    output: Dict[str, Any],
    rotation_quat: np.ndarray,
    euler_xyz_deg: np.ndarray,
    focal_length_mm: float,
    camera_intrinsics_json: Optional[Path],
) -> Dict[str, Any]:
    """Build pose.json payload."""
    transform_data: Dict[str, Any] = {}
    for key in sorted(KEYS_TO_SAVE):
        if key in output:
            transform_data[key] = _to_jsonable(output[key])
        else:
            print(f"    Warning: key not found in output: {key}")

    transform_data["rotation_quaternion_wxyz"] = rotation_quat.tolist()
    transform_data["rotation_euler_xyz_degrees"] = euler_xyz_deg.tolist()
    transform_data["rotation_euler_order"] = "XYZ"
    transform_data["focal_length_mm_used_for_overlay"] = float(focal_length_mm)
    if camera_intrinsics_json is not None:
        transform_data["camera_intrinsics_json"] = str(camera_intrinsics_json)
    return transform_data


def save_outputs(
    output: Dict[str, Any],
    output_dir: Path,
    mesh_format: str = "ply",
    image_rgb: np.ndarray = None,
    focal_length_mm: float = 50.0,
    camera_intrinsics_json: Optional[Path] = None,
) -> trimesh.Trimesh | None:
    """Save canonical mesh, posed mesh, and transform data.

    Saves:
        - output_dir/mesh.<format> (canonical mesh)
        - output_dir/pose.json (transform keys + Euler XYZ degrees + camera json path)
        - output_dir/mesh_posed.<format> (mesh in camera frame)
        - output_dir/mesh_posed_overlay.png (posed mesh overlaid on source image)

    Coordinate Notes:
        - SAM3D transforms are in Z-up coordinate system.
        - GLB exports:
            1. Canonical and posed meshes are exported in Y-up.
            2. pose.json stores transform values in Z-up.
        - PLY exports:
            1. Canonical mesh comes directly from SAM3D mesh output (Z-up).
            2. Posed mesh is exported in Z-up.
            3. pose.json stores transform values in Z-up.

    Args:
        output: SAM 3D Objects output dictionary.
        output_dir: Directory to save outputs.
        mesh_format: Output mesh format ("ply" or "glb").
        image_rgb: Source image for overlay rendering.
        focal_length_mm: Focal length in mm for perspective projection.
        camera_intrinsics_json: Optional path to frame-level intrinsics JSON.

    Returns:
        The posed mesh in Y-up (GLB) or Z-up (PLY) coordinates.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    canonical_mesh, mesh_ext, canonical_is_y_up = _resolve_canonical_mesh(output, mesh_format)

    canonical_mesh_path = output_dir / f"mesh.{mesh_ext}"
    canonical_mesh.export(str(canonical_mesh_path))
    print(f"    Saved: mesh.{mesh_ext} (canonical)")

    rotation_quat, translation, scale = _extract_pose_components(output)
    euler_xyz_deg = quaternion_to_euler_xyz_degrees(rotation_quat)

    print(f"    Rotation (quat): {rotation_quat}")
    print(f"    Rotation (euler xyz deg): {euler_xyz_deg}")
    print(f"    Translation: {translation}")
    print(f"    Scale: {scale}")

    transform_data = _build_transform_data(
        output=output,
        rotation_quat=rotation_quat,
        euler_xyz_deg=euler_xyz_deg,
        focal_length_mm=focal_length_mm,
        camera_intrinsics_json=camera_intrinsics_json,
    )

    # Save pose.json (always saved)
    pose_path = output_dir / "pose.json"
    with open(pose_path, "w") as f:
        json.dump(transform_data, f, indent=2)
    print("    Saved: pose.json")

    # Create posed mesh (handles Y-up <-> Z-up conversions internally)
    posed_mesh = create_posed_mesh(
        canonical_mesh,
        rotation_quat,
        translation,
        scale,
        canonical_is_y_up=canonical_is_y_up,
    )

    posed_mesh_path = output_dir / f"mesh_posed.{mesh_ext}"
    posed_mesh.export(str(posed_mesh_path))
    print(f"    Saved: mesh_posed.{mesh_ext} (posed)")

    # Render individual overlay if image provided
    if image_rgb is not None:
        overlay = render_posed_mesh_overlay(
            image_rgb,
            posed_mesh,
            mesh_is_y_up=canonical_is_y_up,
            focal_length_mm=focal_length_mm
        )
        overlay_path = output_dir / "mesh_posed_overlay.png"
        cv2.imwrite(str(overlay_path), overlay)
        print("    Saved: mesh_posed_overlay.png")

    return posed_mesh


def _resolve_path_maybe_relative(path_like: str | Path, base_dir: Path) -> Path:
    """Resolve a potentially relative path against base_dir."""
    path = Path(path_like)
    if not path.is_absolute():
        path = base_dir / path
    return path.resolve()


def _object_slug(obj_info: Dict[str, Any]) -> str:
    """Resolve stable object slug used for mesh output directory names."""
    output_dir = obj_info.get("output_dir")
    if output_dir:
        return Path(str(output_dir)).name
    return str(obj_info.get("object", "object")).replace(" ", "_")


def process_from_summary(
    summary_path: Path,
    sam3d,
    mesh_output_root: Path,
    mesh_format: str = "ply",
    focal_length_mm: Optional[float] = None,
) -> None:
    """Process all objects from a segmentation summary file.

    Args:
        summary_path: Path to segmentation summary JSON.
        sam3d: SAM 3D Objects inference instance.
        mesh_output_root: Root directory for mesh outputs.
        mesh_format: Output mesh format ("ply" or "glb").
        focal_length_mm: Focal length in mm for overlay rendering.
            If None, estimated from MoGe intrinsics.

    Also saves:
        - Individual overlay per object: <object_dir>/mesh_posed_overlay.png
        - Combined overlay: <mesh_output_root>/<video_xx>/<frame_name>_all_objects_overlay.png
    """
    with open(summary_path) as f:
        summary = json.load(f)

    segmentation_root = summary_path.parent
    video_name = segmentation_root.name
    output_root = (mesh_output_root / video_name).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    source_image_path = _resolve_path_maybe_relative(
        summary["source_image"],
        segmentation_root,
    )
    frame_name = summary["source_frame"]

    print(f"Processing frame: {frame_name}")
    print(f"Source image: {source_image_path}")
    print(f"Segmentation dir: {segmentation_root}")
    print(f"Mesh output dir: {output_root}")

    image_bgr = cv2.imread(str(source_image_path))
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image_path}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    camera_info = estimate_camera_intrinsics_from_moge(sam3d, image_rgb)

    if camera_info is None:
        h, w = image_rgb.shape[:2]
        fallback_fx = float(DEFAULT_FOCAL_LENGTH_MM) * float(w) / float(SENSOR_WIDTH_MM)
        fallback_fy = float(DEFAULT_FOCAL_LENGTH_MM) * float(h) / float(SENSOR_HEIGHT_MM)
        fallback_cx = float(w) / 2.0
        fallback_cy = float(h) / 2.0
        camera_info = {
            "source": "fallback_default",
            "intrinsics_pixels_3x3": [
                [fallback_fx, 0.0, fallback_cx],
                [0.0, fallback_fy, fallback_cy],
                [0.0, 0.0, 1.0],
            ],
            "blender_recommendation": {
                "sensor_fit": "HORIZONTAL",
                "lens_mm": float(DEFAULT_FOCAL_LENGTH_MM),
                "sensor_width_mm": float(SENSOR_WIDTH_MM),
                "sensor_height_mm": float(SENSOR_HEIGHT_MM),
                "note": "MoGe intrinsics estimation failed; using default focal length.",
            },
        }

    if focal_length_mm is None:
        resolved_focal_length_mm = float(
            camera_info["blender_recommendation"]["lens_mm"]
        )
        print(f"Using auto focal length: {resolved_focal_length_mm:.2f}mm")
    else:
        resolved_focal_length_mm = float(focal_length_mm)
        print(f"Using user-provided focal length: {resolved_focal_length_mm:.2f}mm")

    camera_intrinsics_json = output_root / "camera_intrinsics.json"
    save_camera_intrinsics_json(camera_info, camera_intrinsics_json)

    # Collect posed meshes for combined overlay
    posed_meshes = []
    object_names = []

    for obj_info in summary["objects"]:
        if not obj_info.get("success", False):
            print(f"\nSkipping {obj_info['object']} (segmentation failed)")
            continue

        obj_name = obj_info["object"]
        object_slug = _object_slug(obj_info)
        seg_output_dir_raw = obj_info.get("output_dir")
        if seg_output_dir_raw:
            seg_output_dir = _resolve_path_maybe_relative(
                str(seg_output_dir_raw),
                segmentation_root,
            )
        else:
            seg_output_dir = (segmentation_root / object_slug).resolve()

        mask_file = obj_info.get("mask_file")
        if not mask_file:
            print(f"  Error: Missing mask_file for {obj_name}")
            continue

        print(f"\n{'=' * 50}")
        print(f"Processing: {obj_name}")

        mask_path = _resolve_path_maybe_relative(str(mask_file), seg_output_dir)
        if not mask_path.exists():
            print(f"  Error: Mask not found: {mask_path}")
            continue

        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            print(f"  Error: Could not read mask: {mask_path}")
            continue

        mask = (mask > 127).astype(np.uint8)
        print(f"  Loaded mask: {mask_file}")

        print("  Generating mesh...")
        try:
            output = generate_mesh(sam3d, image_rgb, mask)

            # Print a couple of common stats if present (kept lightweight).
            if "scale" in output:
                try:
                    scale_val = _to_jsonable(output["scale"])
                    print(f"    Scale: {scale_val}")
                except Exception:
                    pass
            if "translation" in output:
                try:
                    trans_val = _to_jsonable(output["translation"])
                    print(f"    Translation: {trans_val}")
                except Exception:
                    pass

            # Save canonical and posed meshes with individual overlay.
            object_output_dir = output_root / object_slug
            posed_mesh = save_outputs(
                output,
                object_output_dir,
                mesh_format=mesh_format,
                image_rgb=image_rgb,
                focal_length_mm=resolved_focal_length_mm,
                camera_intrinsics_json=camera_intrinsics_json,
            )

            # Collect for combined overlay
            if posed_mesh is not None:
                posed_meshes.append(posed_mesh)
                object_names.append(obj_name)

        except Exception as e:
            print(f"  Mesh generation failed: {e}")

    # Generate combined overlay with all posed objects.
    if posed_meshes:
        print(f"\n{'=' * 50}")
        print("Generating combined overlay with all posed objects...")
        combined_overlay = render_all_posed_meshes_overlay(
            image_rgb,
            posed_meshes,
            object_names,
            mesh_is_y_up=(mesh_format == "glb"),
            focal_length_mm=resolved_focal_length_mm,
        )
        combined_overlay_path = output_root / f"{frame_name}_all_objects_overlay.png"
        cv2.imwrite(str(combined_overlay_path), combined_overlay)
        print(f"Saved: {combined_overlay_path}")


def resolve_summary_path(input_dir: Path) -> Path:
    """Resolve segmentation summary JSON from a segmentation directory."""
    if not input_dir.exists() or not input_dir.is_dir():
        raise NotADirectoryError(f"Input directory not found: {input_dir}")

    summary_files = sorted(input_dir.glob("*_segmentation_summary.json"))
    if not summary_files:
        raise FileNotFoundError(
            "No segmentation summary JSON found in directory: "
            f"{input_dir}. Expected '*_segmentation_summary.json'."
        )
    if len(summary_files) > 1:
        raise ValueError(
            "Multiple segmentation summary JSON files found in directory: "
            f"{input_dir}. Found: {[str(p.name) for p in summary_files]}"
        )

    return summary_files[0]


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate canonical and posed 3D meshes from a segmentation summary JSON "
        "(run with sam3d-objects env)."
    )
    parser.add_argument(
        "--input_dir",
        type=str,
        default="../Segment_First_Frame/output/video_03",
        help="Segmentation directory containing '*_segmentation_summary.json'.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./output",
        help="Mesh output root. Final outputs go to <output_dir>/<video_xx>/.",
    )
    parser.add_argument(
        "--focal_length",
        type=float,
        default=None,
        help=(
            "Focal length in mm for perspective projection in overlay rendering. "
            "If omitted, estimate from MoGe intrinsics."
        ),
    )
    parser.add_argument(
        "--mesh_format",
        type=str,
        default="ply",
        choices=["ply", "glb"],
        help="Mesh export format for canonical and posed meshes.",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.is_absolute():
        input_dir = Path(__file__).parent / input_dir
    input_dir = input_dir.resolve()
    summary_path = resolve_summary_path(input_dir)

    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = Path(__file__).parent / output_dir
    output_dir = output_dir.resolve()

    print("Loading SAM 3D Objects...")
    sam3d = load_sam3d()
    print("SAM 3D Objects loaded successfully\n")

    print("Mode: Generating canonical + posed meshes")
    print(f"Segmentation input: {input_dir}")
    print(f"Mesh output root: {output_dir}")
    if args.focal_length is None:
        print("Focal length: auto (MoGe intrinsics)")
    else:
        print(f"Focal length: {args.focal_length}mm")
    print(f"Mesh format: {args.mesh_format}")
    print()

    process_from_summary(
        summary_path,
        sam3d,
        mesh_output_root=output_dir,
        mesh_format=args.mesh_format,
        focal_length_mm=args.focal_length
    )

    print(f"\n{'=' * 50}")
    print("Done!")


if __name__ == "__main__":
    main()
