"""
Generate 3D meshes from pre-computed segmentation masks.

This script reads a segmentation summary JSON (generated by segment_frame.py)
and uses SAM 3D Objects to generate canonical 3D meshes.

Run this script with the sam3d-objects environment.

Pipeline:
    1. Read segmentation summary JSON
    2. Use SAM 3D Objects to generate 3D mesh from each mask
    3. Save output to each object's output_dir:
        - mesh.glb (canonical mesh, Y-up coordinate system)
        - pose.json (transform keys: rotation, translation, scale)
        - mesh_posed.glb (mesh transformed to camera frame, Y-up)
        - mesh_posed_overlay.png (posed mesh overlaid on source image)
    4. Save combined overlay:
        - <frame_name>_all_objects_overlay.png (all posed objects on source image)

Coordinate System Notes:
    - GLB files are Y-up by convention
    - SAM 3D Objects outputs transforms in Z-up coordinate system
    - When applying transforms:
        1. Convert mesh from Y-up to Z-up
        2. Apply transforms (scale -> rotate -> translate)
        3. Convert back to Y-up for GLB export
    - Blender automatically converts Y-up to Z-up on import

Rendering Notes (from render_posed_mesh.py):
    - PyTorch3D uses: +X is left, +Y is up
    - Screen space uses: +X is right, +Y is down
    - Convert coordinates with F_P3D_TO_CV before projection
    - Source: https://github.com/facebookresearch/sam-3d-objects/issues/56

Usage:
    conda activate sam3d-objects

    # Generate canonical + posed meshes and overlays
    python generate_object_meshes.py --summary path/to/frame_00_segmentation_summary.json
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Optional

import cv2
import numpy as np
import torch
import trimesh

# Configuration
SAM3D_PATH = "/my_workspace/4DHHOI/sam-3d-objects"

KEYS_TO_SAVE = {
    "6drotation_normalized",
    "rotation",
    "translation",
    "scale",
    "translation_scale",
}


# =============================================================================
# Coordinate Transformation Utilities
# =============================================================================
# GLB files are stored in Y-up coordinate system.
# SAM 3D Objects outputs transforms in Z-up coordinate system.
# We need to convert between these two coordinate systems.

# Rotation matrix to convert Y-up to Z-up coordinates
# This rotates vertices so that Y-up becomes Z-up
R_Y_UP_TO_Z_UP = np.array([
    [1, 0, 0],
    [0, 0, -1],
    [0, 1, 0],
], dtype=np.float32)

# Rotation matrix to convert Z-up to Y-up coordinates (inverse of above)
R_Z_UP_TO_Y_UP = np.array([
    [1, 0, 0],
    [0, 0, 1],
    [0, -1, 0],
], dtype=np.float32)

# P3D camera coords (+X left, +Y up, +Z forward) to OpenCV (+X right, +Y down, +Z forward)
F_P3D_TO_CV = np.diag([-1.0, -1.0, 1.0]).astype(np.float32)

SENSOR_WIDTH_MM = 36.0  # Full-frame sensor width for focal length conversion
SENSOR_HEIGHT_MM = 24.0  # Full-frame sensor height for focal length conversion
DEFAULT_FOCAL_LENGTH_MM = 24.0


def estimate_camera_intrinsics_from_moge(
    sam3d: Any,
    image_rgb: np.ndarray,
    sensor_width_mm: float = SENSOR_WIDTH_MM,
    sensor_height_mm: float = SENSOR_HEIGHT_MM,
) -> Optional[Dict[str, Any]]:
    """Estimate camera intrinsics from MoGe and derive focal lengths in mm."""
    try:
        pipeline = getattr(sam3d, "_pipeline", None)
        if pipeline is None:
            raise AttributeError("SAM3D inference object has no '_pipeline' attribute")

        depth_model = getattr(pipeline, "depth_model", None)
        if depth_model is None:
            raise AttributeError("SAM3D pipeline has no 'depth_model' attribute")

        h, w = image_rgb.shape[:2]
        image_tensor = torch.from_numpy(image_rgb).permute(2, 0, 1).float() / 255.0

        with torch.no_grad():
            depth_output = depth_model(image_tensor)

        intrinsics = depth_output.get("intrinsics", None)
        if intrinsics is None:
            raise ValueError("MoGe output did not contain 'intrinsics'")

        if hasattr(intrinsics, "detach"):
            intrinsics = intrinsics.detach().cpu().numpy()
        else:
            intrinsics = np.asarray(intrinsics)

        if intrinsics.ndim == 3:
            intrinsics = intrinsics[0]

        # MoGe intrinsics are normalized to image size.
        fx_px = float(intrinsics[0, 0]) * w
        fy_px = float(intrinsics[1, 1]) * h
        cx_px = float(intrinsics[0, 2]) * w
        cy_px = float(intrinsics[1, 2]) * h

        focal_mm_x = fx_px * sensor_width_mm / float(w)
        focal_mm_y = fy_px * sensor_height_mm / float(h)

        intrinsics_px = np.array(
            [
                [fx_px, 0.0, cx_px],
                [0.0, fy_px, cy_px],
                [0.0, 0.0, 1.0],
            ],
            dtype=np.float32,
        )

        # Recommended single lens value for Blender with sensor fit=HORIZONTAL.
        focal_mm_recommended = focal_mm_x

        camera_info = {
            "source": "moge_from_sam3d_depth_model",
            "image_size_px": {"width": int(w), "height": int(h)},
            "intrinsics_normalized_3x3": intrinsics.tolist(),
            "intrinsics_pixels_3x3": intrinsics_px.tolist(),
            "fx_px": fx_px,
            "fy_px": fy_px,
            "cx_px": cx_px,
            "cy_px": cy_px,
            "sensor_width_mm_assumed": float(sensor_width_mm),
            "sensor_height_mm_assumed": float(sensor_height_mm),
            "focal_length_mm_x": float(focal_mm_x),
            "focal_length_mm_y": float(focal_mm_y),
            "focal_length_mm_recommended": float(focal_mm_recommended),
            "blender_recommendation": {
                "sensor_fit": "HORIZONTAL",
                "lens_mm": float(focal_mm_recommended),
                "sensor_width_mm": float(sensor_width_mm),
                "sensor_height_mm": float(sensor_height_mm),
                "note": "Lens uses fx with full-frame horizontal fit.",
            },
        }

        print(
            "Auto-estimated intrinsics from MoGe: "
            f"fx={fx_px:.1f}px, fy={fy_px:.1f}px | "
            f"lens={focal_mm_recommended:.2f}mm (recommended)"
        )
        return camera_info

    except Exception as e:
        print(f"Warning: failed to estimate intrinsics from MoGe ({e}).")
        return None


def save_camera_intrinsics_json(camera_info: Dict[str, Any], output_path: Path) -> None:
    """Save camera intrinsics metadata to JSON."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(camera_info, f, indent=2)
    print(f"Saved: {output_path}")


def render_posed_mesh_overlay(
    image: np.ndarray,
    posed_mesh: trimesh.Trimesh,
    focal_length_mm: float = 50.0,
    color: tuple = (0, 255, 0),
    point_radius: int = 1,
) -> np.ndarray:
    """Render posed mesh vertices overlaid on an image.

    Perspective projection uses a coordinate conversion matrix:
        P3D (+X left, +Y up, +Z forward) to OpenCV
        (+X right, +Y down, +Z forward).

    Args:
        image: RGB image as numpy array (H, W, 3).
        posed_mesh: Mesh in Y-up coordinates (as stored in GLB).
        focal_length_mm: Focal length in millimeters (default: 50mm).
        color: BGR color tuple for rendering vertices.
        point_radius: Radius of rendered points.

    Returns:
        Image with mesh vertices overlaid (BGR format for cv2).
    """
    h, w = image.shape[:2]
    result = image.copy()

    # Get vertices and convert to BGR for OpenCV
    if len(result.shape) == 3 and result.shape[2] == 3:
        # Check if RGB, convert to BGR for cv2 operations
        result = cv2.cvtColor(result, cv2.COLOR_RGB2BGR)

    # Get vertices from posed mesh (Y-up) and convert to Z-up for projection
    vertices_y_up = np.array(posed_mesh.vertices, dtype=np.float32)
    vertices_z_up = vertices_y_up @ R_Y_UP_TO_Z_UP.T

    # Get vertex colors if available
    vertex_colors = None
    if hasattr(posed_mesh, 'visual') and hasattr(posed_mesh.visual, 'vertex_colors'):
        vertex_colors = posed_mesh.visual.vertex_colors

    # Perspective projection parameters
    # Convert focal length from mm to pixels
    # Assuming full-frame sensor (36mm width) as reference
    focal_length = focal_length_mm * w / SENSOR_WIDTH_MM
    cx, cy = w / 2, h / 2

    # Filter points behind camera (z > 0.1)
    z = vertices_z_up[:, 2]
    valid_mask = z > 0.1
    pts_valid = vertices_z_up[valid_mask]
    pts_valid_cv = pts_valid @ F_P3D_TO_CV.T
    z_valid = pts_valid_cv[:, 2]

    if len(pts_valid) == 0:
        return result

    # Project to 2D in OpenCV camera coordinates.
    u = ((pts_valid_cv[:, 0] * focal_length) / z_valid + cx).astype(int)
    v = ((pts_valid_cv[:, 1] * focal_length) / z_valid + cy).astype(int)

    # Filter points within image bounds
    in_view = (u >= 0) & (u < w) & (v >= 0) & (v < h)
    u_final, v_final = u[in_view], v[in_view]

    # Draw points with vertex colors or specified color
    if vertex_colors is not None:
        valid_colors = vertex_colors[valid_mask][in_view]
        for i in range(len(u_final)):
            c = valid_colors[i]
            # Convert RGBA/RGB to BGR for OpenCV
            cv2.circle(
                result,
                (u_final[i], v_final[i]),
                point_radius,
                (int(c[2]), int(c[1]), int(c[0])),
                -1,
            )
    else:
        for i in range(len(u_final)):
            cv2.circle(result, (u_final[i], v_final[i]), point_radius, color, -1)

    return result


def render_all_posed_meshes_overlay(
    image: np.ndarray,
    posed_meshes: list,
    object_names: list,
    focal_length_mm: float = 50.0,
    point_radius: int = 1,
) -> np.ndarray:
    """Render multiple posed meshes overlaid on a single image.

    Each object gets a distinct color if vertex colors are not available.

    Args:
        image: RGB image as numpy array (H, W, 3).
        posed_meshes: List of meshes in Y-up coordinates.
        object_names: List of object names (for labeling).
        focal_length_mm: Focal length in millimeters (default: 50mm).
        point_radius: Radius of rendered points.

    Returns:
        Image with all mesh vertices overlaid (BGR format).
    """
    h, w = image.shape[:2]
    result = cv2.cvtColor(image.copy(), cv2.COLOR_RGB2BGR)

    # Generate distinct colors for each object (if no vertex colors)
    # Using HSV color wheel for distinct colors
    num_objects = len(posed_meshes)
    object_colors = []
    for i in range(num_objects):
        hue = int(180 * i / max(num_objects, 1))  # OpenCV HSV hue is 0-180
        hsv_color = np.array([[[hue, 255, 255]]], dtype=np.uint8)
        bgr_color = cv2.cvtColor(hsv_color, cv2.COLOR_HSV2BGR)[0, 0]
        object_colors.append(tuple(map(int, bgr_color)))

    # Perspective projection parameters
    # Convert focal length from mm to pixels (assuming 36mm sensor width)
    sensor_width_mm = 36.0
    focal_length = focal_length_mm * w / sensor_width_mm
    cx, cy = w / 2, h / 2

    for idx, (posed_mesh, obj_name) in enumerate(zip(posed_meshes, object_names)):
        # Get vertices and convert to Z-up for projection
        vertices_y_up = np.array(posed_mesh.vertices, dtype=np.float32)
        vertices_z_up = vertices_y_up @ R_Y_UP_TO_Z_UP.T

        # Get vertex colors if available
        vertex_colors = None
        if hasattr(posed_mesh, 'visual') and hasattr(posed_mesh.visual, 'vertex_colors'):
            vertex_colors = posed_mesh.visual.vertex_colors

        # Filter points behind camera
        z = vertices_z_up[:, 2]
        valid_mask = z > 0.1
        pts_valid = vertices_z_up[valid_mask]
        pts_valid_cv = pts_valid @ F_P3D_TO_CV.T
        z_valid = pts_valid_cv[:, 2]

        if len(pts_valid) == 0:
            continue

        # Project in OpenCV camera coordinates.
        u = ((pts_valid_cv[:, 0] * focal_length) / z_valid + cx).astype(int)
        v = ((pts_valid_cv[:, 1] * focal_length) / z_valid + cy).astype(int)

        # Filter in view
        in_view = (u >= 0) & (u < w) & (v >= 0) & (v < h)
        u_final, v_final = u[in_view], v[in_view]

        # Draw points
        if vertex_colors is not None:
            valid_colors = vertex_colors[valid_mask][in_view]
            for i in range(len(u_final)):
                c = valid_colors[i]
                cv2.circle(
                    result, (u_final[i], v_final[i]), point_radius,
                    (int(c[2]), int(c[1]), int(c[0])), -1
                )
        else:
            color = object_colors[idx]
            for i in range(len(u_final)):
                cv2.circle(result, (u_final[i], v_final[i]), point_radius, color, -1)

    # Add legend with object names and colors
    y_offset = 30
    for idx, obj_name in enumerate(object_names):
        color = object_colors[idx]
        cv2.rectangle(result, (10, y_offset - 15), (30, y_offset), color, -1)
        cv2.putText(
            result, obj_name, (40, y_offset), cv2.FONT_HERSHEY_SIMPLEX,
            0.5, (255, 255, 255), 1, cv2.LINE_AA
        )
        y_offset += 25

    return result


def quaternion_to_rotation_matrix(quat: np.ndarray) -> np.ndarray:
    """Convert quaternion (w, x, y, z) to 3x3 rotation matrix.

    PyTorch3D uses (w, x, y, z) quaternion convention.

    Args:
        quat: Quaternion as numpy array of shape (4,) in (w, x, y, z) format.

    Returns:
        3x3 rotation matrix as numpy array.
    """
    w, x, y, z = quat

    # Normalize quaternion
    norm = np.sqrt(w*w + x*x + y*y + z*z)
    w, x, y, z = w/norm, x/norm, y/norm, z/norm

    # Build rotation matrix
    rot = np.array([
        [1 - 2*(y*y + z*z), 2*(x*y - z*w), 2*(x*z + y*w)],
        [2*(x*y + z*w), 1 - 2*(x*x + z*z), 2*(y*z - x*w)],
        [2*(x*z - y*w), 2*(y*z + x*w), 1 - 2*(x*x + y*y)],
    ], dtype=np.float32)

    return rot


def quaternion_to_euler_xyz_degrees(quat: np.ndarray) -> np.ndarray:
    """Convert quaternion (w, x, y, z) to Euler XYZ angles in degrees."""
    w, x, y, z = quat

    norm = np.sqrt(w * w + x * x + y * y + z * z)
    w, x, y, z = w / norm, x / norm, y / norm, z / norm

    # XYZ Tait-Bryan angles
    t0 = 2.0 * (w * x + y * z)
    t1 = 1.0 - 2.0 * (x * x + y * y)
    roll_x = np.arctan2(t0, t1)

    t2 = 2.0 * (w * y - z * x)
    t2 = np.clip(t2, -1.0, 1.0)
    pitch_y = np.arcsin(t2)

    t3 = 2.0 * (w * z + x * y)
    t4 = 1.0 - 2.0 * (y * y + z * z)
    yaw_z = np.arctan2(t3, t4)

    return np.degrees(np.array([roll_x, pitch_y, yaw_z], dtype=np.float32))


def apply_transform_to_vertices(
    vertices: np.ndarray,
    scale: np.ndarray,
    rotation: np.ndarray,
    translation: np.ndarray,
) -> np.ndarray:
    """Apply scale, rotation, and translation to vertices.

    Transform order (same as PyTorch3D Transform3d composition):
        1. Scale
        2. Rotate
        3. Translate

    Args:
        vertices: (N, 3) array of vertex positions.
        scale: (3,) array of scale factors.
        rotation: (3, 3) rotation matrix.
        translation: (3,) translation vector.

    Returns:
        (N, 3) array of transformed vertices.
    """
    # 1. Apply scale
    scaled = vertices * scale

    # 2. Apply rotation
    # PyTorch3D Transform3d.rotate(R) uses v @ R convention
    # Our quaternion_to_rotation_matrix produces the same matrix as PyTorch3D
    rotated = scaled @ rotation

    # 3. Apply translation
    translated = rotated + translation

    return translated


def create_posed_mesh(
    canonical_mesh: trimesh.Trimesh,
    rotation_quat: np.ndarray,
    translation: np.ndarray,
    scale: np.ndarray,
) -> trimesh.Trimesh:
    """Create a posed mesh from canonical mesh and transforms.

    Coordinate System Handling:
        - GLB canonical mesh is in Y-up coordinate system
        - SAM 3D Objects transforms are in Z-up coordinate system
        - We convert Y-up -> Z-up, apply transforms, then Z-up -> Y-up
        - This ensures the output GLB is still Y-up (as per GLB convention)
        - Blender will automatically convert Y-up to Z-up on import

    Transform Pipeline:
        1. Convert vertices from Y-up to Z-up
        2. Apply transforms in Z-up space (scale -> rotate -> translate)
        3. Convert vertices back from Z-up to Y-up
        4. Return mesh ready for GLB export (Y-up)

    Args:
        canonical_mesh: The canonical mesh (Y-up, from GLB).
        rotation_quat: Quaternion (w, x, y, z) from SAM 3D Objects.
        translation: Translation vector (3,) from SAM 3D Objects.
        scale: Scale factors (3,) from SAM 3D Objects.

    Returns:
        Posed mesh in Y-up coordinates (ready for GLB export).
    """
    # Get vertices from canonical mesh
    vertices = np.array(canonical_mesh.vertices, dtype=np.float32)

    # Step 1: Convert Y-up to Z-up
    # GLB is Y-up, but SAM3D transforms are in Z-up context
    # Original render script: verts = torch.matmul(verts, r_y2z.T)
    vertices_z_up = vertices @ R_Y_UP_TO_Z_UP.T

    # Step 2: Convert quaternion to rotation matrix
    rotation_matrix = quaternion_to_rotation_matrix(rotation_quat)

    # Step 3: Apply transforms in Z-up space
    vertices_posed = apply_transform_to_vertices(
        vertices_z_up,
        scale,
        rotation_matrix,
        translation,
    )

    # Step 4: Convert back to Y-up for GLB export
    # Blender will auto-convert Y-up to Z-up on import
    # This is the inverse of the Y-up to Z-up conversion
    vertices_y_up = vertices_posed @ R_Z_UP_TO_Y_UP.T

    # Create new mesh with transformed vertices
    posed_mesh = canonical_mesh.copy()
    posed_mesh.vertices = vertices_y_up

    return posed_mesh


def load_sam3d():
    """Load SAM 3D Objects inference pipeline."""
    notebook_path = Path(SAM3D_PATH) / "notebook"
    if str(notebook_path) not in sys.path:
        sys.path.insert(0, str(notebook_path))

    from inference import Inference

    possible_paths = [
        Path(SAM3D_PATH) / "checkpoints" / "hf" / "pipeline.yaml",
        Path(SAM3D_PATH)
        / "checkpoints"
        / "hf-download"
        / "checkpoints"
        / "pipeline.yaml",
    ]

    config_path = None
    for p in possible_paths:
        if p.exists():
            config_path = p
            break

    if config_path is None:
        tried = [str(p) for p in possible_paths]
        raise FileNotFoundError(f"SAM3D config not found. Tried: {tried}")

    print(f"Loading SAM 3D Objects from: {config_path}")
    return Inference(str(config_path), compile=False)


def generate_mesh(inference, image: np.ndarray, mask: np.ndarray) -> dict:
    """Generate 3D mesh using SAM 3D Objects.

    Args:
        inference: SAM3D Inference instance
        image: RGB image as numpy array
        mask: Binary mask as numpy array

    Returns:
        Output dictionary with glb and transform fields.
    """
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)
    if mask.dtype != bool:
        mask = mask > 0

    return inference(image, mask, seed=42)


def _to_jsonable(value: Any) -> Any:
    """Convert common tensor/numpy types to JSON-serializable Python types."""
    if value is None:
        return None

    # torch tensors (without importing torch)
    if hasattr(value, "detach") and hasattr(value, "cpu"):
        value = value.detach().cpu()

    if hasattr(value, "numpy"):
        value = value.numpy()

    if isinstance(value, np.ndarray):
        if value.size == 1:
            return float(value.reshape(-1)[0])
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


def save_outputs(
    output: Dict[str, Any],
    output_dir: Path,
    image_rgb: np.ndarray = None,
    focal_length_mm: float = 50.0,
    camera_intrinsics_json: Optional[Path] = None,
) -> trimesh.Trimesh | None:
    """Save canonical mesh, posed mesh, and transform data.

    Saves:
        - output_dir/mesh.glb (canonical mesh in Y-up; NOT scaled/transformed)
        - output_dir/pose.json (transform keys + Euler XYZ degrees + camera json path)
        - output_dir/mesh_posed.glb (mesh in camera frame, Y-up)
        - output_dir/mesh_posed_overlay.png (posed mesh overlaid on source image)

    Coordinate Notes:
        - Canonical mesh.glb is in Y-up (GLB convention)
        - pose.json contains transforms in Z-up coordinate system
        - Posed mesh_posed.glb is saved in Y-up for GLB convention
        - Blender auto-converts Y-up to Z-up on import

    Args:
        output: SAM 3D Objects output dictionary.
        output_dir: Directory to save outputs.
        image_rgb: Source image for overlay rendering.
        focal_length_mm: Focal length in mm for perspective projection.
        camera_intrinsics_json: Optional path to frame-level intrinsics JSON.

    Returns:
        The posed mesh in Y-up coordinates.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if "glb" not in output or output["glb"] is None:
        raise ValueError("Output does not contain a mesh ('glb').")

    canonical_mesh = output["glb"]

    # Save canonical mesh (Y-up, unscaled)
    glb_path = output_dir / "mesh.glb"
    canonical_mesh.export(str(glb_path))
    print("    Saved: mesh.glb (canonical, Y-up)")

    required_keys = {"rotation", "translation", "scale"}
    missing_keys = sorted(required_keys.difference(output))
    if missing_keys:
        raise ValueError(f"Missing transform keys for posed mesh: {missing_keys}")

    rotation_quat = np.array(
        _to_jsonable(output["rotation"]),
        dtype=np.float32,
    ).flatten()
    translation = np.array(
        _to_jsonable(output["translation"]),
        dtype=np.float32,
    ).flatten()
    scale = np.array(
        _to_jsonable(output["scale"]),
        dtype=np.float32,
    ).flatten()
    euler_xyz_deg = quaternion_to_euler_xyz_degrees(rotation_quat)

    print(f"    Rotation (quat): {rotation_quat}")
    print(f"    Rotation (euler xyz deg): {euler_xyz_deg}")
    print(f"    Translation: {translation}")
    print(f"    Scale: {scale}")

    # Build transform data for pose.json
    transform_data: Dict[str, Any] = {}
    for key in sorted(KEYS_TO_SAVE):
        if key in output:
            transform_data[key] = _to_jsonable(output[key])
        else:
            print(f"    Warning: key not found in output: {key}")
    transform_data["rotation_quaternion_wxyz"] = rotation_quat.tolist()
    transform_data["rotation_euler_xyz_degrees"] = euler_xyz_deg.tolist()
    transform_data["rotation_euler_order"] = "XYZ"
    transform_data["focal_length_mm_used_for_overlay"] = float(focal_length_mm)
    if camera_intrinsics_json is not None:
        transform_data["camera_intrinsics_json"] = str(camera_intrinsics_json)

    # Save pose.json (always saved)
    pose_path = output_dir / "pose.json"
    with open(pose_path, "w") as f:
        json.dump(transform_data, f, indent=2)
    print("    Saved: pose.json")

    # Create posed mesh (handles Y-up <-> Z-up conversions internally)
    posed_mesh = create_posed_mesh(
        canonical_mesh,
        rotation_quat,
        translation,
        scale,
    )

    # Save posed mesh (Y-up for GLB convention)
    posed_glb_path = output_dir / "mesh_posed.glb"
    posed_mesh.export(str(posed_glb_path))
    print("    Saved: mesh_posed.glb (posed, Y-up, Blender auto-converts to Z-up)")

    # Render individual overlay if image provided
    if image_rgb is not None:
        overlay = render_posed_mesh_overlay(
            image_rgb,
            posed_mesh,
            focal_length_mm=focal_length_mm
        )
        overlay_path = output_dir / "mesh_posed_overlay.png"
        cv2.imwrite(str(overlay_path), overlay)
        print("    Saved: mesh_posed_overlay.png")

    return posed_mesh


def process_from_summary(
    summary_path: Path,
    sam3d,
    focal_length_mm: Optional[float] = None,
) -> None:
    """Process all objects from a segmentation summary file.

    Args:
        summary_path: Path to segmentation summary JSON.
        sam3d: SAM 3D Objects inference instance.
        focal_length_mm: Focal length in mm for overlay rendering.
            If None, estimated from MoGe intrinsics.

    Also saves:
        - Individual overlay per object: <object_dir>/mesh_posed_overlay.png
        - Combined overlay: <output_root>/<frame_name>_all_objects_overlay.png
    """
    with open(summary_path) as f:
        summary = json.load(f)

    source_image_path = summary["source_image"]
    frame_name = summary["source_frame"]
    output_root = summary_path.parent  # Directory containing the summary file

    print(f"Processing frame: {frame_name}")
    print(f"Source image: {source_image_path}")

    image_bgr = cv2.imread(source_image_path)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image_path}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    camera_info = estimate_camera_intrinsics_from_moge(sam3d, image_rgb)

    if camera_info is None:
        h, w = image_rgb.shape[:2]
        camera_info = {
            "source": "fallback_default",
            "image_size_px": {"width": int(w), "height": int(h)},
            "sensor_width_mm_assumed": float(SENSOR_WIDTH_MM),
            "sensor_height_mm_assumed": float(SENSOR_HEIGHT_MM),
            "focal_length_mm_recommended": float(DEFAULT_FOCAL_LENGTH_MM),
            "note": "MoGe intrinsics estimation failed; using default focal length.",
        }

    if focal_length_mm is None:
        resolved_focal_length_mm = float(
            camera_info.get("focal_length_mm_recommended", DEFAULT_FOCAL_LENGTH_MM)
        )
        print(f"Using auto focal length: {resolved_focal_length_mm:.2f}mm")
    else:
        resolved_focal_length_mm = float(focal_length_mm)
        print(f"Using user-provided focal length: {resolved_focal_length_mm:.2f}mm")

    camera_info["focal_length_mm_used_for_overlay"] = float(resolved_focal_length_mm)
    if focal_length_mm is not None:
        camera_info["focal_length_mm_user_override"] = float(focal_length_mm)

    camera_intrinsics_json = output_root / "camera_intrinsics.json"
    save_camera_intrinsics_json(camera_info, camera_intrinsics_json)

    # Collect posed meshes for combined overlay
    posed_meshes = []
    object_names = []

    for obj_info in summary["objects"]:
        if not obj_info.get("success", False):
            print(f"\nSkipping {obj_info['object']} (segmentation failed)")
            continue

        obj_name = obj_info["object"]
        output_dir = Path(obj_info["output_dir"])
        mask_file = obj_info["mask_file"]

        print(f"\n{'=' * 50}")
        print(f"Processing: {obj_name}")

        mask_path = output_dir / mask_file
        if not mask_path.exists():
            print(f"  Error: Mask not found: {mask_path}")
            continue

        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            print(f"  Error: Could not read mask: {mask_path}")
            continue

        mask = (mask > 127).astype(np.uint8)
        print(f"  Loaded mask: {mask_file}")

        print("  Generating mesh...")
        try:
            output = generate_mesh(sam3d, image_rgb, mask)

            # Print a couple of common stats if present (kept lightweight).
            if "scale" in output:
                try:
                    scale_val = _to_jsonable(output["scale"])
                    print(f"    Scale: {scale_val}")
                except Exception:
                    pass
            if "translation" in output:
                try:
                    trans_val = _to_jsonable(output["translation"])
                    print(f"    Translation: {trans_val}")
                except Exception:
                    pass

            # Save canonical and posed meshes with individual overlay.
            posed_mesh = save_outputs(
                output,
                output_dir,
                image_rgb=image_rgb,
                focal_length_mm=resolved_focal_length_mm,
                camera_intrinsics_json=camera_intrinsics_json,
            )

            # Collect for combined overlay
            if posed_mesh is not None:
                posed_meshes.append(posed_mesh)
                object_names.append(obj_name)

        except Exception as e:
            print(f"  Mesh generation failed: {e}")

    # Generate combined overlay with all posed objects.
    if posed_meshes:
        print(f"\n{'=' * 50}")
        print("Generating combined overlay with all posed objects...")
        combined_overlay = render_all_posed_meshes_overlay(
            image_rgb,
            posed_meshes,
            object_names,
            focal_length_mm=resolved_focal_length_mm,
        )
        combined_overlay_path = output_root / f"{frame_name}_all_objects_overlay.png"
        cv2.imwrite(str(combined_overlay_path), combined_overlay)
        print(f"Saved: {combined_overlay_path}")


def resolve_summary_path(input_dir: Path) -> Path:
    """Resolve segmentation summary JSON from an input directory."""
    if not input_dir.exists() or not input_dir.is_dir():
        raise NotADirectoryError(f"Input directory not found: {input_dir}")

    summary_files = sorted(input_dir.glob("*_segmentation_summary.json"))
    if not summary_files:
        raise FileNotFoundError(
            "No segmentation summary JSON found in directory: "
            f"{input_dir}. Expected '*_segmentation_summary.json'."
        )
    if len(summary_files) > 1:
        raise ValueError(
            "Multiple segmentation summary JSON files found in directory: "
            f"{input_dir}. Found: {[str(p.name) for p in summary_files]}"
        )

    return summary_files[0]


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate canonical and posed 3D meshes from a segmentation summary JSON "
        "(run with sam3d-objects env)."
    )
    parser.add_argument(
        "--input_dir",
        type=str,
        default="./output/video_01",
        help="Directory containing '*_segmentation_summary.json'.",
    )
    parser.add_argument(
        "--focal_length",
        type=float,
        default=None,
        help=(
            "Focal length in mm for perspective projection in overlay rendering. "
            "If omitted, estimate from MoGe intrinsics."
        ),
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.is_absolute():
        input_dir = Path(__file__).parent / input_dir
    input_dir = input_dir.resolve()
    summary_path = resolve_summary_path(input_dir)

    print("Loading SAM 3D Objects...")
    sam3d = load_sam3d()
    print("SAM 3D Objects loaded successfully\n")

    print("Mode: Generating canonical + posed meshes")
    if args.focal_length is None:
        print("Focal length: auto (MoGe intrinsics)")
    else:
        print(f"Focal length: {args.focal_length}mm")
    print()

    process_from_summary(
        summary_path,
        sam3d,
        focal_length_mm=args.focal_length
    )

    print(f"\n{'=' * 50}")
    print("Done!")


if __name__ == "__main__":
    main()
