"""
Generate 3D meshes from pre-computed segmentation masks.

This script reads a segmentation summary JSON (generated by segment_frame.py)
and uses SAM 3D Objects to generate canonical 3D meshes.

Run this script with the sam3d-objects environment.

Pipeline:
    1. Read segmentation summary JSON
    2. Use SAM 3D Objects to generate canonical 3D mesh from each mask
    3. Save output to each object's output_dir:
        - mesh.glb (canonical mesh)
        - transform.json (selected transform keys)

Usage:
    conda activate sam3d-objects
    python generate_object_meshes.py --summary path/to/frame_00_segmentation_summary.json
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

import cv2
import numpy as np

# Configuration
SAM3D_PATH = "/my_workspace/4DHHOI/sam-3d-objects"

KEYS_TO_SAVE = {
    "6drotation_normalized",
    "rotation",
    "translation",
    "scale",
    "translation_scale",
}


def load_sam3d():
    """Load SAM 3D Objects inference pipeline."""
    notebook_path = Path(SAM3D_PATH) / "notebook"
    if str(notebook_path) not in sys.path:
        sys.path.insert(0, str(notebook_path))

    from inference import Inference

    possible_paths = [
        Path(SAM3D_PATH) / "checkpoints" / "hf" / "pipeline.yaml",
        Path(SAM3D_PATH)
        / "checkpoints"
        / "hf-download"
        / "checkpoints"
        / "pipeline.yaml",
    ]

    config_path = None
    for p in possible_paths:
        if p.exists():
            config_path = p
            break

    if config_path is None:
        tried = [str(p) for p in possible_paths]
        raise FileNotFoundError(f"SAM3D config not found. Tried: {tried}")

    print(f"Loading SAM 3D Objects from: {config_path}")
    return Inference(str(config_path), compile=False)


def generate_mesh(inference, image: np.ndarray, mask: np.ndarray) -> dict:
    """Generate 3D mesh using SAM 3D Objects.

    Args:
        inference: SAM3D Inference instance
        image: RGB image as numpy array
        mask: Binary mask as numpy array

    Returns:
        Output dictionary with glb and transform fields.
    """
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)
    if mask.dtype != bool:
        mask = mask > 0

    return inference(image, mask, seed=42)


def _to_jsonable(value: Any) -> Any:
    """Convert common tensor/numpy types to JSON-serializable Python types."""
    if value is None:
        return None

    # torch tensors (without importing torch)
    if hasattr(value, "detach") and hasattr(value, "cpu"):
        value = value.detach().cpu()

    if hasattr(value, "numpy"):
        value = value.numpy()

    if isinstance(value, np.ndarray):
        if value.size == 1:
            return float(value.reshape(-1)[0])
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


def save_outputs(output: Dict[str, Any], output_dir: Path) -> None:
    """Save canonical mesh and selected transform data.

    Saves:
        - output_dir/mesh.glb (canonical mesh; NOT scaled)
        - output_dir/transform.json (selected keys from output)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if "glb" not in output or output["glb"] is None:
        raise ValueError("Output does not contain a mesh ('glb').")

    glb_path = output_dir / "mesh.glb"
    output["glb"].export(str(glb_path))
    print("    Saved: mesh.glb")

    transform_data: Dict[str, Any] = {}
    for key in sorted(KEYS_TO_SAVE):
        if key in output:
            transform_data[key] = _to_jsonable(output[key])
        else:
            print(f"    Warning: key not found in output: {key}")

    transform_path = output_dir / "transform.json"
    with open(transform_path, "w") as f:
        json.dump(transform_data, f, indent=2)
    print("    Saved: transform.json")


def process_from_summary(summary_path: Path, sam3d) -> None:
    """Process all objects from a segmentation summary file."""
    with open(summary_path) as f:
        summary = json.load(f)

    source_image_path = summary["source_image"]
    frame_name = summary["source_frame"]

    print(f"Processing frame: {frame_name}")
    print(f"Source image: {source_image_path}")

    image_bgr = cv2.imread(source_image_path)
    if image_bgr is None:
        print(f"Error: Could not load source image: {source_image_path}")
        return
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    for obj_info in summary["objects"]:
        if not obj_info.get("success", False):
            print(f"\nSkipping {obj_info['object']} (segmentation failed)")
            continue

        obj_name = obj_info["object"]
        output_dir = Path(obj_info["output_dir"])
        mask_file = obj_info["mask_file"]

        print(f"\n{'=' * 50}")
        print(f"Processing: {obj_name}")

        mask_path = output_dir / mask_file
        if not mask_path.exists():
            print(f"  Error: Mask not found: {mask_path}")
            continue

        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            print(f"  Error: Could not read mask: {mask_path}")
            continue

        mask = (mask > 127).astype(np.uint8)
        print(f"  Loaded mask: {mask_file}")

        print("  Generating mesh...")
        try:
            output = generate_mesh(sam3d, image_rgb, mask)

            # Print a couple of common stats if present (kept lightweight).
            if "scale" in output:
                try:
                    scale_val = _to_jsonable(output["scale"])
                    print(f"    Scale: {scale_val}")
                except Exception:
                    pass
            if "translation" in output:
                try:
                    trans_val = _to_jsonable(output["translation"])
                    print(f"    Translation: {trans_val}")
                except Exception:
                    pass

            # Save CANONICAL mesh.
            save_outputs(output, output_dir)
        except Exception as e:
            print(f"  Mesh generation failed: {e}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate canonical 3D meshes from a segmentation summary JSON "
        "(run with sam3d-objects env)."
    )
    parser.add_argument(
        "--summary",
        type=str,
        default="./objects/video_01/frame_00_segmentation_summary.json",
        help="Path to segmentation summary JSON.",
    )
    args = parser.parse_args()

    summary_path = Path(args.summary)
    if not summary_path.exists():
        print(f"Error: Summary file not found: {summary_path}")
        return

    print("Loading SAM 3D Objects...")
    sam3d = load_sam3d()
    print("SAM 3D Objects loaded successfully\n")

    process_from_summary(summary_path, sam3d)

    print(f"\n{'=' * 50}")
    print("Done!")


if __name__ == "__main__":
    main()
